name = "TerraFirmaGreg-1.20.x"
author = "Exception, Xikaro"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28d6a68c6b752c4c8ba41735f506d0203d177100519fc837c40e06f26fd6c7dc"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
meta-folder-base = "modpack"
