name = "TerraFirmaGreg-1.20.x"
author = "Exception, Xikaro"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d965d012c7aa321d78347632b9928c0572b669894edd77a189a66ad7a6f1141"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
