name = "TerraFirmaGreg-1.20.x"
author = "Exception, Xikaro"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91161875d79853ad447016a224498577e794f45bfa3ff9f9210b393e909020c1"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
meta-folder-base = ".github/buildtools/modpack"
