
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 385053
	#The name of the modpack
	modpackName = "TerraFirmaGreg"
	#The version of the modpack
	modpackVersion = "DEV"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

