#The ratio of the eu to the fe energy converting - Default: (1.0 EU = 8.0 FE)
#Range: 0.1 ~ 1.7976931348623157E308
EU_TO_FE_RATIO = 8.0
#The ratio of the eu to the tre energy converting - Default: (1.0 EU = 1.0 TRE)
#Range: 0.1 ~ 1.7976931348623157E308
EU_TO_TRE_RATIO = 1.0
#Enables GT Machines and  cables being able to input FE or TRE(Tech Reborn Energy),
#Please do not enable unless you have balanced the fe compat to not be broken due to power creep. - Default: false
ENABLE_FE_OR_TRE_INPUT = false
#Enables Tesseract energy having compat with MI energy. - Default: false
ENABLE_MI_COMPAT = true

