name: Deploy modpack preview

on:
  push:
    tags:
      - "Pre*"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/Pre}

      - name: Archive MMC
        run: |
          git submodule init
          cd mods
          git config --local credential.helper '!f() { sleep 1; echo "password=secrets.USER_TOKEN_XIKARO"; }; f'
          git config --local http.https://github.com.Xikaro.extraheader "AUTHORIZATION: basic $(git credential-cache get)"
          git config --local url."https://github.com/Xikaro:secrets.USER_TOKEN_XIKARO@github.com".insteadOf "https://github.com/TerraFirmaGreg-Team/TFG-Mods-1.20.x"
          git submodule update --recursive