name: Deploy modpack preview

on:
  push:
    tags:
      - "Pre*"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/Pre}

      - name: Archive MMC
        run: |
          git submodule init
          cd mods
          git config --global credential.helper '!f() { echo "username=Xikaro"; echo "password=${{ secrets.USER_TOKEN_XIKARO }}"; }; f'
          git submodule update --recursive