name: Deploy modpack preview

on:
  push:
    tags:
      - "Pre*"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/Pre}

      - name: Set the version
        run: |
          DEV=${{ steps.get_version.outputs.version }}
          sed -i -e "s/DEV/${DEV}/g" pack.toml
          sed -i -e "s/DEV/${DEV}/g" config/fancymenu/customization/main_menu.txt
          sed -i -e "s/DEV/${DEV}/g" config/bcc-common.toml

      - name: Changelog Parser
        id: changelog
        uses: coditory/changelog-parser@v1.0.2
        with:
          path: CHANGELOG.md

      - name: Set up Go 1.19
        id: go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.19
      - run: go install github.com/packwiz/packwiz@latest

      - name: Archive CF
        run: |
          cd ./
          packwiz curseforge export

      - name: Archive MMC
        run: |
          mkdir -p .minecraft
          cp -r ./{config,defaultconfigs,kubejs,mods,.github/buildtools/modpack/mmc-pack.json,.github/buildtools/modpack/instance.cfg} .minecraft/
          zip -r ./TerraFirmaGreg-1.20.x-${{ steps.get_version.outputs.version }}-mmc.zip .minecraft/

      - name: Archive Server
        run: |
          cp -r .github/buildtools/serverpack/* .minecraft/
          cat .github/buildtools/client_mod.txt | while read -r line; do find .minecraft/mods -name "$line" -delete; done
          cd .minecraft/
          zip -r ../TerraFirmaGreg-1.20.x-${{ steps.get_version.outputs.version }}-server.zip ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
          name: Release ${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.description }}
          files: |
            ./TerraFirmaGreg-1.20.x-${{ steps.get_version.outputs.version }}.zip
            ./TerraFirmaGreg-1.20.x-${{ steps.get_version.outputs.version }}-mmc.zip
            ./TerraFirmaGreg-1.20.x-${{ steps.get_version.outputs.version }}-server.zip
